// Generated by CoffeeScript 1.4.0
(function() {
  var GetBalance, GetBalanceError, GetBalanceSuccess, GetLog, GetLogSuccess, GetTaxes, GetTaxesSuccess;

  GetBalanceSuccess = function(value) {
    if (value != null) {
      return $('#balance_value').text(value);
    } else {
      return alert("GetBalance failed!");
    }
  };

  GetBalanceError = function() {
    return alert("GetBalance failed!");
  };

  GetTaxesSuccess = function(value) {
    var rows, tax;
    if (value != null) {
      rows = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = value.length; _i < _len; _i++) {
          tax = value[_i];
          _results.push("<tr><td>" + tax.Name + "</td><td>" + tax.Cost + "</td><td><a class='btn btn-link' href='#''><i class='' icon-pencil'></i></a><a class='btn btn-link' href='#'><i class='icon-trash'></i></a></td></tr>");
        }
        return _results;
      })();
      return $("#taxesTable").append(rows.join(""));
    } else {
      return alert("GetTaxes failed!");
    }
  };

  GetLogSuccess = function(value) {
    var log, rows;
    if (value != null) {
      rows = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = value.length; _i < _len; _i++) {
          log = value[_i];
          _results.push("<tr><td>" + log.Date + "</td><td>" + log.Comment + "</td><td class='log_value log_positive'>" + log.Amount + "</td></tr>");
        }
        return _results;
      })();
      return $("#logsTable").append(rows.join(""));
    } else {
      return alert("GetLogs failed!");
    }
  };

  GetBalance = function() {
    return SendAjax("/api/ballance", "", GetBalanceSuccess, GetBalanceError, "GET");
  };

  GetTaxes = function() {
    return SendAjax("/api/taxes", null, GetTaxesSuccess, null, "GET");
  };

  GetLog = function() {
    return SendAjax("/api/log", null, GetLogSuccess, null, "GET");
  };

  $(function() {
    GetBalance();
    GetTaxes();
    return GetLog();
  });

}).call(this);
