// Generated by CoffeeScript 1.4.0
(function() {
  var AddBalance, AddBalanceSuccess, AddTaxes, AddTaxesSuccess, DeleteTaxSuccess, DeleteTaxes, GetBalance, GetBalanceError, GetBalanceSuccess, GetLog, GetLogSuccess, GetTaxes, GetTaxesSuccess, PayAll, PayAllSuccess;

  GetBalanceSuccess = function(value) {
    if (value != null) {
      return $('#balance_value').text(value);
    } else {
      return alert("GetBalance failed!");
    }
  };

  GetBalanceError = function() {
    return alert("GetBalance failed!");
  };

  GetTaxesSuccess = function(value) {
    var rows, tax;
    if (value != null) {
      rows = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = value.length; _i < _len; _i++) {
          tax = value[_i];
          _results.push("<tr><td>" + tax.Name + "</td><td>" + tax.Cost + "</td><td><a class='btn btn-link' href='#''><i class='' icon-pencil'></i></a><a class='btn btn-link' href='#'><i class='icon-trash' data-name='" + tax.Name + "'></i></a></td></tr>");
        }
        return _results;
      })();
      $("#taxesTable tbody").html("");
      return $("#taxesTable").append(rows.join(""));
    } else {
      return alert("GetTaxes failed!");
    }
  };

  GetLogSuccess = function(value) {
    var date, dateString, log, rows;
    if (value != null) {
      rows = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = value.length; _i < _len; _i++) {
          log = value[_i];
          date = new Date(parseInt(/\d+/g.exec("/Date(1355063352862)/")[0]));
          dateString = date.getDate() + "." + (date.getMonth() + 1) + "." + date.getFullYear() + " " + date.getHours() + ":" + date.getMinutes();
          _results.push("<tr><td>" + dateString + "</td><td>" + log.Comment + "</td><td class='log_value log_positive'>" + log.Amount + "</td></tr>");
        }
        return _results;
      })();
      $("#logsTable tbody").html("");
      return $("#logsTable").append(rows.join(""));
    } else {
      return alert("GetLogs failed!");
    }
  };

  GetBalance = function() {
    return SendAjax("/api/ballance", "", GetBalanceSuccess, GetBalanceError, "GET");
  };

  GetTaxes = function() {
    return SendAjax("/api/taxes", null, GetTaxesSuccess, null, "GET");
  };

  AddBalanceSuccess = function(value) {
    GetBalance();
    return GetLog();
  };

  PayAllSuccess = function(value) {
    GetBalance();
    return GetLog();
  };

  AddTaxesSuccess = function(value) {
    return GetTaxes();
  };

  DeleteTaxSuccess = function(value) {
    return GetTaxes();
  };

  AddBalance = function() {
    var data;
    data = {
      Diff: $("#addAmount").val(),
      Comment: $("#addComment").val()
    };
    return SendAjax("/api/ballance", data, AddBalanceSuccess, null, "POST");
  };

  AddTaxes = function() {
    var data;
    data = {
      Name: $("#taxesName").val(),
      Cost: $("#taxesValue").val()
    };
    return SendAjax("/api/taxes", data, AddTaxesSuccess, null, "PUT");
  };

  PayAll = function() {
    return SendAjax("/api/TaxProcessing", null, PayAllSuccess, null, "GET");
  };

  DeleteTaxes = function(element) {
    var data;
    data = {
      Name: $(element).data("name")
    };
    return SendAjax("/api/taxes", data, DeleteTaxSuccess, null, "DELETE");
  };

  GetLog = function() {
    return SendAjax("/api/log", null, GetLogSuccess, null, "GET");
  };

  $(function() {
    $('#addBalance').bind('click', function(event) {
      event.preventDefault();
      return AddBalance();
    });
    $('#addTax').bind('click', function(event) {
      event.preventDefault();
      return AddTaxes();
    });
    $('.icon-trash').live('click', function(event) {
      event.preventDefault();
      return DeleteTaxes($(this));
    });
    $('#payAll').bind('click', function(event) {
      event.preventDefault();
      return PayAll();
    });
    GetBalance();
    GetTaxes();
    return GetLog();
  });

}).call(this);
