// Generated by CoffeeScript 1.4.0
(function() {
  var GetBalance, GetBalanceError, GetBalanceSuccess;

  GetBalanceSuccess = function(value) {
    if (value != null) {
      return $('#balance_value').val(value);
    } else {
      return alert("GetBalance failed!");
    }
  };

  GetBalanceError = function() {
    return alert("GetBalance failed!");
  };

  GetBalance = function() {
    return SendAjax("/api/balance", "", GetBalanceSuccess, GetBalanceError, "GET");
  };

}).call(this);
