// Generated by CoffeeScript 1.4.0
(function() {
  var LoginError, LoginSuccess;

  LoginSuccess = function(authkey) {
    if (authkey != null) {
      SetCookie("sessionId", authkey);
      return window.location.href = "main.html";
    } else {
      return $('#showError').append('<p class="error_message">Incorrect email or password,<br> Please try again</p>');
    }
  };

  LoginError = function() {
    return $('#showError').append('<p class="error_message">Incorrect email or password,<br> Please try again</p>');
  };

  $(function() {
    $('#signin').bind('click', function(event) {
      var data;
      event.preventDefault();
      $('.error_message').remove();
      data = {
        email: $("#inputEmail").val(),
        password: $("#inputPassword").val()
      };
      return SendAjax("/api/signin", data, LoginSuccess, LoginError, "POST");
    });
    return $('#signup').bind('click', function(event) {
      var data;
      event.preventDefault();
      $('.error_message').remove();
      data = {
        email: $("#inputEmail").val(),
        password: $("#inputPassword").val()
      };
      return SendAjax("/api/signup", data, LoginSuccess, LoginError, "POST");
    });
  });

}).call(this);
