// Generated by CoffeeScript 1.4.0
(function() {

  this.GetCookie = function(name) {
    var pattern, regexp;
    pattern = "(?:; )?" + name + "=([^;]*);?";
    regexp = new RegExp(pattern);
    if (regexp.test(document.cookie)) {
      return decodeURIComponent(RegExp["$1"]);
    }
    return false;
  };

  this.SetCookie = function(name, value) {
    var str;
    if (!name || !value) {
      return false;
    }
    str = name + '=' + encodeURIComponent(value);
    document.cookie = str;
    return true;
  };

  this.SendAjax = function(controller, data, success, error, type) {
    var params,
      _this = this;
    params = {
      type: type,
      dataType: "json",
      url: controller,
      data: data,
      headers: {
        AuthKey: GetCookie("sessionId")
      },
      success: function(data) {
        return success(data);
      },
      error: function(data) {
        return error(data);
      }
    };
    return $.ajax(params);
  };

  this.ClearInput = function(id) {
    return $(id).val("");
  };

}).call(this);
